@URL=http://localhost
@PORT=3003
@baseUrl={{URL}}:{{PORT}}


# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{ 
    "username": "testimiu",
    "password": "salasana"
}



#########################
@authToken = {{login.response.body.token}}

POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: bearer {{authToken}}

{ 
    "title": "Miuku  taas vol 5",
    "author": "miuku",
    "likes": 15,
    "url": "www.miuu.fi"
}
