@URL=http://localhost
@PORT=3003
@baseUrl={{URL}}:{{PORT}}


# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{ 
    "username": "testimiu",
    "password": "salasana"
}



#########################

@deleting_blog_ID=63e7e53b2be16e1aefad15b5


@authToken={{login.response.body.token}}

DELETE {{baseUrl}}/api/blogs/{{deleting_blog_ID}}
Content-Type: application/json
Authorization: bearer {{authToken}}